trigger:
  branches:
    include:
      - main   # or whichever branches you want to trigger on

pool:
  name: 'Default'   # Your self-hosted agent pool name

stages:
# ---------------------
# CI Stage -> Jenkins
# ---------------------
- stage: CI
  displayName: "Trigger Jenkins Pipeline"
  jobs:
  - job: TriggerJenkins
    displayName: "Run Jenkins CI/CD"
    steps:
    - task: Bash@3
      displayName: "Trigger Jenkins Build"
      inputs:
        targetType: 'inline'
        script: |
          echo "Triggering Jenkins pipeline..."
          curl -X POST "http://20.40.43.80:8080//job/lost-found-pipeline/build" \
            --user " shanmuk:11176f30ee7828b6dbc251fecdf069df33"

# ---------------------
# CD Stage -> Terraform
# ---------------------
- stage: CD
  displayName: "Deploy to AKS with Terraform"
  dependsOn: CI
  jobs:
  - job: TerraformDeploy
    displayName: "Run Terraform Deployment"
    steps:
    - task: Bash@3
      displayName: "Terraform Init/Plan/Apply"
      inputs:
        targetType: 'inline'
        script: |
          set -euo pipefail
          
          echo "Starting Terraform deployment..."

          cd terraform

          # Initialize Terraform
          terraform init -input=false

          # Validate configs
          terraform validate

          # Plan
          terraform plan -out=tfplan -input=false

          # Apply
          terraform apply -input=false tfplan
          
          echo "Terraform deployment complete!"
