trigger:
- main

pool:
  name: 'Default'  # Your self-hosted agent pool
  demands:
  - agent.name -equals agent2

stages:
# ------------------
# Stage 1: Trigger Jenkins
# ------------------
- stage: CI
  displayName: "Run Jenkins CI"
  jobs:
  - job: TriggerJenkins
    displayName: "Trigger Jenkins Pipeline"
    steps:
    - bash: |
        echo "Triggering Jenkins job..."
        curl -X POST "http://20.40.43.80:8080//job/lost-found-pipeline/build" \
          --user "shanmuk:11176f30ee7828b6dbc251fecdf069df33"
      displayName: "Trigger Jenkins Build"

# ------------------
# Stage 2: Terraform Deploy
# ------------------
- stage: CD
  displayName: "Deploy App to AKS"
  dependsOn: CI
  jobs:
  - job: Terraform
    displayName: "Terraform Deploy"
    steps:
    - checkout: self

    # Verify Terraform exists
    - bash: terraform -version
      displayName: "Check Terraform"

    # Run Terraform
    - task: AzureCLI@2
      displayName: "Terraform Init & Apply"
      inputs:
        azureSubscription: 'myAzureRMServiceConnection'   # <-- reuse your working service connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Working directory: $(Build.SourcesDirectory)"
          ls -R $(Build.SourcesDirectory)

          cd $(Build.SourcesDirectory)/terraform   # <-- your terraform folder
          terraform init -input=false
          terraform validate
          terraform plan -out=tfplan -input=false
          terraform apply -input=false tfplan

