trigger:
- main

pool:
  name: 'Default'  # Self-hosted agent
  demands:
  - agent.name -equals agent2

variables:
  TF_DIR: 'terraform'        # Folder containing main.tf + k8s-deploy.tf
  JENKINS_JOB: 'lost-found-pipeline'
  JENKINS_URL: 'http://20.40.43.80:8080'
  JENKINS_USER: 'shanmuk'
  JENKINS_TOKEN: '11176f30ee7828b6dbc251fecdf069df33'
  AZURE_SERVICE_CONNECTION: 'myAzureRMServiceConnection'

stages:
# -------------------------
# Stage 1: Trigger Jenkins
# -------------------------
- stage: CI
  displayName: "Run Jenkins CI"
  jobs:
  - job: TriggerJenkins
    displayName: "Trigger Jenkins Pipeline"
    steps:
    - bash: |
        echo "Triggering Jenkins job..."
        curl -X POST "$(JENKINS_URL)/job/$(JENKINS_JOB)/build" \
          --user "$(JENKINS_USER):$(JENKINS_TOKEN)"
      displayName: "Trigger Jenkins Build"

# -------------------------
# Stage 2: Terraform Deploy
# -------------------------
- stage: CD
  displayName: "Deploy App to AKS"
  dependsOn: CI
  jobs:
  - job: Terraform
    displayName: "Terraform Deploy"
    steps:
    # Checkout repo
    - checkout: self

    # Verify Terraform installed
    - bash: terraform -version
      displayName: "Check Terraform"

    # Terraform Init & Apply using AzureCLI authentication
    - task: AzureCLI@2
      displayName: "Terraform Init & Apply"
      inputs:
        azureSubscription: myAzureRMServiceConnection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Working directory: $(Build.SourcesDirectory)/$(TF_DIR)"
          cd $(Build.SourcesDirectory)/$(TF_DIR)

          # Initialize Terraform
          terraform init -input=false

          # Validate Terraform files
          terraform validate

          # Plan & apply (uses AzureCLI authentication, no SP vars needed)
          terraform plan -out=tfplan -input=false
          terraform apply -input=false -auto-approve tfplan

    # Output Frontend LoadBalancer IP
    - bash: |
        cd $(Build.SourcesDirectory)/$(TF_DIR)
        echo "Frontend LoadBalancer IP:"
        terraform output frontend_service_ip
      displayName: "Get Frontend LB IP"
