trigger:
- main

pool:
  name: 'Default'  # Self-hosted agent
  demands:
  - agent.name -equals agent2

variables:
  TF_DIR: 'terraform'        # Folder containing main.tf + k8s-deploy.tf
  JENKINS_JOB: 'lost-found-pipeline'
  JENKINS_URL: 'http://20.40.43.80:8080'
  JENKINS_USER: 'shanmuk'
  JENKINS_TOKEN: '11176f30ee7828b6dbc251fecdf069df33'
  AZURE_SERVICE_CONNECTION: 'myAzureRMServiceConnection'

stages:
# -------------------------
# Stage 1: Trigger Jenkins
# -------------------------
- stage: CI
  displayName: "Run Jenkins CI"
  jobs:
  - job: TriggerJenkins
    displayName: "Trigger Jenkins Pipeline"
    steps:
    - bash: |
        echo "Triggering Jenkins job with BRANCH=main ..."

        # Trigger job and capture queue location (302 redirect in header)
        QUEUE_URL=$(curl -s -X POST "$(JENKINS_URL)/job/$(JENKINS_JOB)/buildWithParameters?BRANCH=main" \
          --user "$(JENKINS_USER):$(JENKINS_TOKEN)" -D - | grep -i Location | awk '{print $2}' | tr -d '\r')

        if [ -z "$QUEUE_URL" ]; then
          echo "Failed to trigger Jenkins job"
          exit 1
        fi

        echo "Job queued at: $QUEUE_URL"

        # Extract queue item number
        QUEUE_ID=$(basename "$QUEUE_URL")
        echo "Queue ID: $QUEUE_ID"

        # Poll Jenkins queue until job starts
        while true; do
          RESPONSE=$(curl -s "$(JENKINS_URL)/queue/item/$QUEUE_ID/api/json" \
            --user "$(JENKINS_USER):$(JENKINS_TOKEN)")

          # Extract 'executable.url' from JSON using grep/sed
          BUILD_URL=$(echo "$RESPONSE" | grep -oP '"executable":\s*{\s*"url":\s*"\K[^"]+')

          if [ -n "$BUILD_URL" ]; then
            echo "Job started at $BUILD_URL"
            break
          fi

          echo "Waiting for job to start..."
          sleep 5
        done

        # Poll Jenkins build until completion
        while true; do
          RESPONSE=$(curl -s "${BUILD_URL}api/json" \
            --user "$(JENKINS_USER):$(JENKINS_TOKEN)")

          # Extract 'result' field
          RESULT=$(echo "$RESPONSE" | grep -oP '"result":\s*"\K[^"]+')

          if [ -n "$RESULT" ] && [ "$RESULT" != "null" ]; then
            echo "Job finished with result: $RESULT"
            if [ "$RESULT" != "SUCCESS" ]; then
              echo "Jenkins job failed!"
              exit 1
            fi
            break
          fi

          echo "Job still running..."
          sleep 10
        done
      displayName: "Trigger Jenkins Build & Wait (no jq)"


# -------------------------
# Stage 2: Terraform Deploy
# -------------------------
- stage: CD
  displayName: "Deploy App to AKS"
  dependsOn: CI
  jobs:
  - job: Terraform
    displayName: "Terraform Deploy"
    steps:
    # Checkout repo
    - checkout: self

    # Verify Terraform installed
    - bash: terraform -version
      displayName: "Check Terraform"

    # Terraform Init & Apply using AzureCLI authentication
    - task: AzureCLI@2
      displayName: "Terraform Init, Import & Apply"
      inputs:
        azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Working directory: $(Build.SourcesDirectory)/$(TF_DIR)"
          cd $(Build.SourcesDirectory)/$(TF_DIR)

          # Export ARM_* env vars for Terraform (uses Azure CLI login from this task)
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)

          # Initialize Terraform
          terraform init -input=false

          # Import existing AKS cluster into Terraform state (ignore if already imported)
          terraform import azurerm_kubernetes_cluster.aks "/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/devops-pipeline-rg/providers/Microsoft.ContainerService/managedClusters/devops-pipeline-aks" || true

          # Validate Terraform files
          terraform validate

          # Plan & apply
          terraform plan -out=tfplan -input=false
          terraform apply -input=false -auto-approve tfplan

    # Output Frontend LoadBalancer IP
    - bash: |
        cd $(Build.SourcesDirectory)/$(TF_DIR)
        echo "Frontend LoadBalancer IP:"
        terraform output frontend_service_ip
      displayName: "Get Frontend LB IP"
